### ISSUE TITLE
Remove $ from code fences

### ISSUE THREAD

**Issue by lukasmalkmus** [watchly/docs#101]
<img width="1920" alt="Screenshot 2021-07-28 at 14 36 03" src="https://user-images.githubusercontent.com/9931588/127326233-4c975c1e-9bf4-4d27-a906-4838a98ad01f.png">

Like the code fences on GitHub, our Docs support copying the content right away. It would be nicer to get rid of the `$ ` signs to support copy and pasting into the terminal.

**Comment by thecraftman** [comment]
Great catch @lukasmalkmus fixed.
