### ISSUE TITLE
go-axiom link points to axiom-cli

### ISSUE THREAD

**Issue by njpatel** [watchly/docs#13]
On this page https://docs.axiom.co/reference/api , the link goes to cli instead of axiom-go

Also,

* `Go-axiom` should be `axiom-go`

**Comment by njpatel** [comment]
> The best way to get started with our API is to use Go-Axiom Send events directly to Axiom API.

Should be

Axiom REST API documentation is coming soon but, in the mean time, the best way to get started building applications on top of Axiom is to use the `axiom-go` library.

**Comment by thecraftman** [comment]
done
