### ISSUE TITLE
Virtual Field page should use tables for all references

### ISSUE THREAD

**Issue by njpatel** [watchly/docs#16]
* Literals
* Arithmetic Operators
* Comparison Operators
* Logical Operators
* String Operators

Should all use the same table format as new functions we added further up the page.

Also

* `String` -> `String Functions`
* `General Utility Functions` -> `Utility Functions`
* `Arithmetic Operators` -> `Math Functions` (the new `Arithmetic Operators`, not the old one that was already there)

**Comment by thecraftman** [comment]
https://docs.axiom.co/reference/virtual-fields/

updated renaming for each operator
