### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by njpatel** [watchly/docs#27]
Right now, going to a page that doesn't exist,  it just shows huge svgs or a blank page.

- https://docs.axiom.co/getting-started/  -> should be a 404 page
- https://docs.axiom.co/getting-started-2 -> should be a 404 page

**Comment by thecraftman** [comment]
similar to: https://github.com/axiomhq/axiom/issues/2168

Closing for now as we will be migrating docs fully to axiom.co
