### ISSUE TITLE
"Data Shippers" links go to broken page

### ISSUE THREAD

**Issue by cdeutsch** [watchly/docs#72]
From this page, https://docs.axiom.co/data-shippers/api, if I click on any link under "Data Shippers" on the left nav, I go to a broken page

![image](https://user-images.githubusercontent.com/404765/118736422-2d0ce100-b808-11eb-8239-1d01d4348583.png)

![image](https://user-images.githubusercontent.com/404765/118736435-35651c00-b808-11eb-9d59-e6bdd6cf745a.png)

**Comment by cdeutsch** [comment]
I'm not actually sure how I got to `https://docs.axiom.co/data-shippers/api`

I did a Google search originally

Seems the links are relative to the current path (ie .`../elastic-beats/`)

I'd make them relative to the site overall (ie. `/data-shippers/elastic-beats/`)

**Comment by cdeutsch** [comment]
I think this is the path I took

- https://www.google.com/search?q=axiom+ingest+api&oq=axiom+&aqs=chrome.0.69i59j69i60l5j69i65l2.1669j0j7&sourceid=chrome&ie=UTF-8
- https://docs.axiom.co/usage/ingest/
- Then I clicked on "Ingest using API" which goes to https://docs.axiom.co/data-shippers/api 

![image](https://user-images.githubusercontent.com/404765/118736995-7dd10980-b809-11eb-85aa-ce49f5ac728c.png)

Note the lack of the `/` at the end of the Url

I think that is breaking things because if I do have the `/` then everything is normal.

**Comment by thecraftman** [comment]
> I'm not actually sure how I got to `https://docs.axiom.co/data-shippers/api`
> 
> I did a Google search originally
> 
> Seems the links are relative to the current path (ie .`../elastic-beats/`)
> 
> I'd make them relative to the site overall (ie. `/data-shippers/elastic-beats/`)



@cdeutsch wow, yes the links are relative to the path.

**Comment by thecraftman** [comment]
Fixed.
