### ISSUE TITLE
Reference -> API page

### ISSUE THREAD

**Issue by cdeutsch** [watchly/docs#74]
https://docs.axiom.co/reference/api/

This page isn't that useful. 

I follow the link to the [Go-Axiom repo](https://github.com/axiomhq/axiom-go#documentation) and then that doesn't have what I'm looking for and says the info on the API is back on the docs site.

I was hoping to see docs on the actual REST endpoints

**Comment by thecraftman** [comment]
Fixed, Thanks @cdeutsch
