### ISSUE TITLE
"The best way to get Axiom running on Kubernetes"

### ISSUE THREAD

**Issue by cdeutsch** [watchly/docs#90]
Are there alternative ways?

If so, should we mention them?

If not, maybe change to to just "To get Axiom running on Kubernetes"

https://docs.axiom.co/install/kubernetes/

![image](https://user-images.githubusercontent.com/404765/123315568-79c39600-d4f1-11eb-9392-65f63c1fd631.png)

**Comment by thecraftman** [comment]
fixed @cdeutsch 

https://docs.axiom.co/reference/visualizations/

**Comment by cdeutsch** [comment]
Thanks @thecraftman 

One more tweak

Change:
"To get Axiom running on Kubernetes is by using our Helm chart."

To:
"To get Axiom running on Kubernetes use our Helm chart."

Sorry about that

**Comment by thecraftman** [comment]
Thanks @cdeutsch it looks proper now. Didn't even read the entire sentence 😅 

Fixing now.
